name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust 1.89+
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.89.0"
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check AVX support
        id: avx
        run: |
          if lscpu | grep -qi 'avx'; then
            echo "AVX_AVAILABLE=true" >> "$GITHUB_ENV"
            echo "AVX support detected."
          else
            echo "AVX_AVAILABLE=false" >> "$GITHUB_ENV"
            echo "AVX support not detected; tests will be skipped." >&2
          fi

      - name: Run tests
        if: env.AVX_AVAILABLE == 'true'
        run: cargo test --workspace --locked

      - name: Skip tests due to missing AVX
        if: env.AVX_AVAILABLE != 'true'
        run: |
          echo "Skipping cargo test because AVX instructions are unavailable on this runner." && exit 0
